//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibe.PCAPredict.Find {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CapturePlus_Interactive_Find_v2_10_ArrayOfResults", Namespace="http://services.postcodeanywhere.co.uk/", ItemName="CapturePlus_Interactive_Find_v2_10_Results")]
    [System.SerializableAttribute()]
    public class CapturePlus_Interactive_Find_v2_10_ArrayOfResults : System.Collections.Generic.List<Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_Results> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapturePlus_Interactive_Find_v2_10_Results", Namespace="http://services.postcodeanywhere.co.uk/")]
    [System.SerializableAttribute()]
    public partial class CapturePlus_Interactive_Find_v2_10_Results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighlightField;
        
        private int CursorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Highlight {
            get {
                return this.HighlightField;
            }
            set {
                if ((object.ReferenceEquals(this.HighlightField, value) != true)) {
                    this.HighlightField = value;
                    this.RaisePropertyChanged("Highlight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cursor {
            get {
                return this.CursorField;
            }
            set {
                if ((this.CursorField.Equals(value) != true)) {
                    this.CursorField = value;
                    this.RaisePropertyChanged("Cursor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Next {
            get {
                return this.NextField;
            }
            set {
                if ((object.ReferenceEquals(this.NextField, value) != true)) {
                    this.NextField = value;
                    this.RaisePropertyChanged("Next");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.postcodeanywhere.co.uk/", ConfigurationName="Find.PostcodeAnywhere_Soap")]
    public interface PostcodeAnywhere_Soap {
        
        // CODEGEN: Generating message contract since the wrapper name (CapturePlus_Interactive_Find_v2_10_Response) of message CapturePlus_Interactive_Find_v2_10Response does not match the default value (CapturePlus_Interactive_Find_v2_10)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.postcodeanywhere.co.uk/CapturePlus_Interactive_Find_v2_10", ReplyAction="*")]
        Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response CapturePlus_Interactive_Find_v2_10(Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://services.postcodeanywhere.co.uk/CapturePlus_Interactive_Find_v2_10", ReplyAction="*")]
        System.IAsyncResult BeginCapturePlus_Interactive_Find_v2_10(Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request request, System.AsyncCallback callback, object asyncState);
        
        Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response EndCapturePlus_Interactive_Find_v2_10(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapturePlus_Interactive_Find_v2_10", WrapperNamespace="http://services.postcodeanywhere.co.uk/", IsWrapped=true)]
    public partial class CapturePlus_Interactive_Find_v2_10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=0)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=1)]
        public string SearchTerm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=2)]
        public string LastId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=3)]
        public string SearchFor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=4)]
        public string Country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=5)]
        public string LanguagePreference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=6)]
        public int MaxSuggestions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=7)]
        public int MaxResults;
        
        public CapturePlus_Interactive_Find_v2_10Request() {
        }
        
        public CapturePlus_Interactive_Find_v2_10Request(string Key, string SearchTerm, string LastId, string SearchFor, string Country, string LanguagePreference, int MaxSuggestions, int MaxResults) {
            this.Key = Key;
            this.SearchTerm = SearchTerm;
            this.LastId = LastId;
            this.SearchFor = SearchFor;
            this.Country = Country;
            this.LanguagePreference = LanguagePreference;
            this.MaxSuggestions = MaxSuggestions;
            this.MaxResults = MaxResults;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CapturePlus_Interactive_Find_v2_10_Response", WrapperNamespace="http://services.postcodeanywhere.co.uk/", IsWrapped=true)]
    public partial class CapturePlus_Interactive_Find_v2_10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=0)]
        public Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults CapturePlus_Interactive_Find_v2_10_Result;
        
        public CapturePlus_Interactive_Find_v2_10Response() {
        }
        
        public CapturePlus_Interactive_Find_v2_10Response(Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults CapturePlus_Interactive_Find_v2_10_Result) {
            this.CapturePlus_Interactive_Find_v2_10_Result = CapturePlus_Interactive_Find_v2_10_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostcodeAnywhere_SoapChannel : Gibe.PCAPredict.Find.PostcodeAnywhere_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CapturePlus_Interactive_Find_v2_10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CapturePlus_Interactive_Find_v2_10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostcodeAnywhere_SoapClient : System.ServiceModel.ClientBase<Gibe.PCAPredict.Find.PostcodeAnywhere_Soap>, Gibe.PCAPredict.Find.PostcodeAnywhere_Soap {
        
        private BeginOperationDelegate onBeginCapturePlus_Interactive_Find_v2_10Delegate;
        
        private EndOperationDelegate onEndCapturePlus_Interactive_Find_v2_10Delegate;
        
        private System.Threading.SendOrPostCallback onCapturePlus_Interactive_Find_v2_10CompletedDelegate;
        
        public PostcodeAnywhere_SoapClient() {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeAnywhere_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CapturePlus_Interactive_Find_v2_10CompletedEventArgs> CapturePlus_Interactive_Find_v2_10Completed;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response Gibe.PCAPredict.Find.PostcodeAnywhere_Soap.CapturePlus_Interactive_Find_v2_10(Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request request) {
            return base.Channel.CapturePlus_Interactive_Find_v2_10(request);
        }
        
        public Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults CapturePlus_Interactive_Find_v2_10(string Key, string SearchTerm, string LastId, string SearchFor, string Country, string LanguagePreference, int MaxSuggestions, int MaxResults) {
            Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request inValue = new Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request();
            inValue.Key = Key;
            inValue.SearchTerm = SearchTerm;
            inValue.LastId = LastId;
            inValue.SearchFor = SearchFor;
            inValue.Country = Country;
            inValue.LanguagePreference = LanguagePreference;
            inValue.MaxSuggestions = MaxSuggestions;
            inValue.MaxResults = MaxResults;
            Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response retVal = ((Gibe.PCAPredict.Find.PostcodeAnywhere_Soap)(this)).CapturePlus_Interactive_Find_v2_10(inValue);
            return retVal.CapturePlus_Interactive_Find_v2_10_Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gibe.PCAPredict.Find.PostcodeAnywhere_Soap.BeginCapturePlus_Interactive_Find_v2_10(Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCapturePlus_Interactive_Find_v2_10(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCapturePlus_Interactive_Find_v2_10(string Key, string SearchTerm, string LastId, string SearchFor, string Country, string LanguagePreference, int MaxSuggestions, int MaxResults, System.AsyncCallback callback, object asyncState) {
            Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request inValue = new Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Request();
            inValue.Key = Key;
            inValue.SearchTerm = SearchTerm;
            inValue.LastId = LastId;
            inValue.SearchFor = SearchFor;
            inValue.Country = Country;
            inValue.LanguagePreference = LanguagePreference;
            inValue.MaxSuggestions = MaxSuggestions;
            inValue.MaxResults = MaxResults;
            return ((Gibe.PCAPredict.Find.PostcodeAnywhere_Soap)(this)).BeginCapturePlus_Interactive_Find_v2_10(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response Gibe.PCAPredict.Find.PostcodeAnywhere_Soap.EndCapturePlus_Interactive_Find_v2_10(System.IAsyncResult result) {
            return base.Channel.EndCapturePlus_Interactive_Find_v2_10(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults EndCapturePlus_Interactive_Find_v2_10(System.IAsyncResult result) {
            Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10Response retVal = ((Gibe.PCAPredict.Find.PostcodeAnywhere_Soap)(this)).EndCapturePlus_Interactive_Find_v2_10(result);
            return retVal.CapturePlus_Interactive_Find_v2_10_Result;
        }
        
        private System.IAsyncResult OnBeginCapturePlus_Interactive_Find_v2_10(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Key = ((string)(inValues[0]));
            string SearchTerm = ((string)(inValues[1]));
            string LastId = ((string)(inValues[2]));
            string SearchFor = ((string)(inValues[3]));
            string Country = ((string)(inValues[4]));
            string LanguagePreference = ((string)(inValues[5]));
            int MaxSuggestions = ((int)(inValues[6]));
            int MaxResults = ((int)(inValues[7]));
            return this.BeginCapturePlus_Interactive_Find_v2_10(Key, SearchTerm, LastId, SearchFor, Country, LanguagePreference, MaxSuggestions, MaxResults, callback, asyncState);
        }
        
        private object[] OnEndCapturePlus_Interactive_Find_v2_10(System.IAsyncResult result) {
            Gibe.PCAPredict.Find.CapturePlus_Interactive_Find_v2_10_ArrayOfResults retVal = this.EndCapturePlus_Interactive_Find_v2_10(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCapturePlus_Interactive_Find_v2_10Completed(object state) {
            if ((this.CapturePlus_Interactive_Find_v2_10Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CapturePlus_Interactive_Find_v2_10Completed(this, new CapturePlus_Interactive_Find_v2_10CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CapturePlus_Interactive_Find_v2_10Async(string Key, string SearchTerm, string LastId, string SearchFor, string Country, string LanguagePreference, int MaxSuggestions, int MaxResults) {
            this.CapturePlus_Interactive_Find_v2_10Async(Key, SearchTerm, LastId, SearchFor, Country, LanguagePreference, MaxSuggestions, MaxResults, null);
        }
        
        public void CapturePlus_Interactive_Find_v2_10Async(string Key, string SearchTerm, string LastId, string SearchFor, string Country, string LanguagePreference, int MaxSuggestions, int MaxResults, object userState) {
            if ((this.onBeginCapturePlus_Interactive_Find_v2_10Delegate == null)) {
                this.onBeginCapturePlus_Interactive_Find_v2_10Delegate = new BeginOperationDelegate(this.OnBeginCapturePlus_Interactive_Find_v2_10);
            }
            if ((this.onEndCapturePlus_Interactive_Find_v2_10Delegate == null)) {
                this.onEndCapturePlus_Interactive_Find_v2_10Delegate = new EndOperationDelegate(this.OnEndCapturePlus_Interactive_Find_v2_10);
            }
            if ((this.onCapturePlus_Interactive_Find_v2_10CompletedDelegate == null)) {
                this.onCapturePlus_Interactive_Find_v2_10CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCapturePlus_Interactive_Find_v2_10Completed);
            }
            base.InvokeAsync(this.onBeginCapturePlus_Interactive_Find_v2_10Delegate, new object[] {
                        Key,
                        SearchTerm,
                        LastId,
                        SearchFor,
                        Country,
                        LanguagePreference,
                        MaxSuggestions,
                        MaxResults}, this.onEndCapturePlus_Interactive_Find_v2_10Delegate, this.onCapturePlus_Interactive_Find_v2_10CompletedDelegate, userState);
        }
    }
}
