//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibe.PCAPredict.Retrieve {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Capture_Interactive_Retrieve_v1_00_ArrayOfResults", Namespace="http://services.postcodeanywhere.co.uk/", ItemName="Capture_Interactive_Retrieve_v1_00_Results")]
    [System.SerializableAttribute()]
    public class Capture_Interactive_Retrieve_v1_00_ArrayOfResults : System.Collections.Generic.List<Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00_Results> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Capture_Interactive_Retrieve_v1_00_Results", Namespace="http://services.postcodeanywhere.co.uk/")]
    [System.SerializableAttribute()]
    public partial class Capture_Interactive_Retrieve_v1_00_Results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomesticIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageAlternativesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighbourhoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminAreaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryIso2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryIso3Field;
        
        private int CountryIsoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortingNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortingNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBoxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field19Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Field20Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DomesticId {
            get {
                return this.DomesticIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DomesticIdField, value) != true)) {
                    this.DomesticIdField = value;
                    this.RaisePropertyChanged("DomesticId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LanguageAlternatives {
            get {
                return this.LanguageAlternativesField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageAlternativesField, value) != true)) {
                    this.LanguageAlternativesField = value;
                    this.RaisePropertyChanged("LanguageAlternatives");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SubBuilding {
            get {
                return this.SubBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.SubBuildingField, value) != true)) {
                    this.SubBuildingField = value;
                    this.RaisePropertyChanged("SubBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SecondaryStreet {
            get {
                return this.SecondaryStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryStreetField, value) != true)) {
                    this.SecondaryStreetField = value;
                    this.RaisePropertyChanged("SecondaryStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Neighbourhood {
            get {
                return this.NeighbourhoodField;
            }
            set {
                if ((object.ReferenceEquals(this.NeighbourhoodField, value) != true)) {
                    this.NeighbourhoodField = value;
                    this.RaisePropertyChanged("Neighbourhood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Line4 {
            get {
                return this.Line4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line4Field, value) != true)) {
                    this.Line4Field = value;
                    this.RaisePropertyChanged("Line4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Line5 {
            get {
                return this.Line5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line5Field, value) != true)) {
                    this.Line5Field = value;
                    this.RaisePropertyChanged("Line5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string AdminAreaName {
            get {
                return this.AdminAreaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminAreaNameField, value) != true)) {
                    this.AdminAreaNameField = value;
                    this.RaisePropertyChanged("AdminAreaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string AdminAreaCode {
            get {
                return this.AdminAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminAreaCodeField, value) != true)) {
                    this.AdminAreaCodeField = value;
                    this.RaisePropertyChanged("AdminAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ProvinceName {
            get {
                return this.ProvinceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceNameField, value) != true)) {
                    this.ProvinceNameField = value;
                    this.RaisePropertyChanged("ProvinceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ProvinceCode {
            get {
                return this.ProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceCodeField, value) != true)) {
                    this.ProvinceCodeField = value;
                    this.RaisePropertyChanged("ProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string CountryIso2 {
            get {
                return this.CountryIso2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryIso2Field, value) != true)) {
                    this.CountryIso2Field = value;
                    this.RaisePropertyChanged("CountryIso2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string CountryIso3 {
            get {
                return this.CountryIso3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CountryIso3Field, value) != true)) {
                    this.CountryIso3Field = value;
                    this.RaisePropertyChanged("CountryIso3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public int CountryIsoNumber {
            get {
                return this.CountryIsoNumberField;
            }
            set {
                if ((this.CountryIsoNumberField.Equals(value) != true)) {
                    this.CountryIsoNumberField = value;
                    this.RaisePropertyChanged("CountryIsoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string SortingNumber1 {
            get {
                return this.SortingNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SortingNumber1Field, value) != true)) {
                    this.SortingNumber1Field = value;
                    this.RaisePropertyChanged("SortingNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string SortingNumber2 {
            get {
                return this.SortingNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SortingNumber2Field, value) != true)) {
                    this.SortingNumber2Field = value;
                    this.RaisePropertyChanged("SortingNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string POBoxNumber {
            get {
                return this.POBoxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.POBoxNumberField, value) != true)) {
                    this.POBoxNumberField = value;
                    this.RaisePropertyChanged("POBoxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string DataLevel {
            get {
                return this.DataLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.DataLevelField, value) != true)) {
                    this.DataLevelField = value;
                    this.RaisePropertyChanged("DataLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string Field1 {
            get {
                return this.Field1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field1Field, value) != true)) {
                    this.Field1Field = value;
                    this.RaisePropertyChanged("Field1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string Field2 {
            get {
                return this.Field2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field2Field, value) != true)) {
                    this.Field2Field = value;
                    this.RaisePropertyChanged("Field2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string Field3 {
            get {
                return this.Field3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field3Field, value) != true)) {
                    this.Field3Field = value;
                    this.RaisePropertyChanged("Field3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Field4 {
            get {
                return this.Field4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field4Field, value) != true)) {
                    this.Field4Field = value;
                    this.RaisePropertyChanged("Field4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string Field5 {
            get {
                return this.Field5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field5Field, value) != true)) {
                    this.Field5Field = value;
                    this.RaisePropertyChanged("Field5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string Field6 {
            get {
                return this.Field6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field6Field, value) != true)) {
                    this.Field6Field = value;
                    this.RaisePropertyChanged("Field6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string Field7 {
            get {
                return this.Field7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field7Field, value) != true)) {
                    this.Field7Field = value;
                    this.RaisePropertyChanged("Field7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string Field8 {
            get {
                return this.Field8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field8Field, value) != true)) {
                    this.Field8Field = value;
                    this.RaisePropertyChanged("Field8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string Field9 {
            get {
                return this.Field9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field9Field, value) != true)) {
                    this.Field9Field = value;
                    this.RaisePropertyChanged("Field9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string Field10 {
            get {
                return this.Field10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field10Field, value) != true)) {
                    this.Field10Field = value;
                    this.RaisePropertyChanged("Field10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string Field11 {
            get {
                return this.Field11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field11Field, value) != true)) {
                    this.Field11Field = value;
                    this.RaisePropertyChanged("Field11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string Field12 {
            get {
                return this.Field12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field12Field, value) != true)) {
                    this.Field12Field = value;
                    this.RaisePropertyChanged("Field12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string Field13 {
            get {
                return this.Field13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field13Field, value) != true)) {
                    this.Field13Field = value;
                    this.RaisePropertyChanged("Field13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string Field14 {
            get {
                return this.Field14Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field14Field, value) != true)) {
                    this.Field14Field = value;
                    this.RaisePropertyChanged("Field14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string Field15 {
            get {
                return this.Field15Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field15Field, value) != true)) {
                    this.Field15Field = value;
                    this.RaisePropertyChanged("Field15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string Field16 {
            get {
                return this.Field16Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field16Field, value) != true)) {
                    this.Field16Field = value;
                    this.RaisePropertyChanged("Field16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string Field17 {
            get {
                return this.Field17Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field17Field, value) != true)) {
                    this.Field17Field = value;
                    this.RaisePropertyChanged("Field17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string Field18 {
            get {
                return this.Field18Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field18Field, value) != true)) {
                    this.Field18Field = value;
                    this.RaisePropertyChanged("Field18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string Field19 {
            get {
                return this.Field19Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field19Field, value) != true)) {
                    this.Field19Field = value;
                    this.RaisePropertyChanged("Field19");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string Field20 {
            get {
                return this.Field20Field;
            }
            set {
                if ((object.ReferenceEquals(this.Field20Field, value) != true)) {
                    this.Field20Field = value;
                    this.RaisePropertyChanged("Field20");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.postcodeanywhere.co.uk/", ConfigurationName="Retrieve.PostcodeAnywhere_Soap")]
    public interface PostcodeAnywhere_Soap {
        
        // CODEGEN: Generating message contract since the wrapper name (Capture_Interactive_Retrieve_v1_00_Response) of message Capture_Interactive_Retrieve_v1_00Response does not match the default value (Capture_Interactive_Retrieve_v1_00)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.postcodeanywhere.co.uk/Capture_Interactive_Retrieve_v1_00", ReplyAction="*")]
        Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response Capture_Interactive_Retrieve_v1_00(Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.postcodeanywhere.co.uk/Capture_Interactive_Retrieve_v1_00", ReplyAction="*")]
        System.Threading.Tasks.Task<Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response> Capture_Interactive_Retrieve_v1_00Async(Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Capture_Interactive_Retrieve_v1_00", WrapperNamespace="http://services.postcodeanywhere.co.uk/", IsWrapped=true)]
    public partial class Capture_Interactive_Retrieve_v1_00Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=0)]
        public string Key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=1)]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=2)]
        public string Field1Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=3)]
        public string Field2Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=4)]
        public string Field3Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=5)]
        public string Field4Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=6)]
        public string Field5Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=7)]
        public string Field6Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=8)]
        public string Field7Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=9)]
        public string Field8Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=10)]
        public string Field9Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=11)]
        public string Field10Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=12)]
        public string Field11Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=13)]
        public string Field12Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=14)]
        public string Field13Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=15)]
        public string Field14Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=16)]
        public string Field15Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=17)]
        public string Field16Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=18)]
        public string Field17Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=19)]
        public string Field18Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=20)]
        public string Field19Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=21)]
        public string Field20Format;
        
        public Capture_Interactive_Retrieve_v1_00Request() {
        }
        
        public Capture_Interactive_Retrieve_v1_00Request(
                    string Key, 
                    string Id, 
                    string Field1Format, 
                    string Field2Format, 
                    string Field3Format, 
                    string Field4Format, 
                    string Field5Format, 
                    string Field6Format, 
                    string Field7Format, 
                    string Field8Format, 
                    string Field9Format, 
                    string Field10Format, 
                    string Field11Format, 
                    string Field12Format, 
                    string Field13Format, 
                    string Field14Format, 
                    string Field15Format, 
                    string Field16Format, 
                    string Field17Format, 
                    string Field18Format, 
                    string Field19Format, 
                    string Field20Format) {
            this.Key = Key;
            this.Id = Id;
            this.Field1Format = Field1Format;
            this.Field2Format = Field2Format;
            this.Field3Format = Field3Format;
            this.Field4Format = Field4Format;
            this.Field5Format = Field5Format;
            this.Field6Format = Field6Format;
            this.Field7Format = Field7Format;
            this.Field8Format = Field8Format;
            this.Field9Format = Field9Format;
            this.Field10Format = Field10Format;
            this.Field11Format = Field11Format;
            this.Field12Format = Field12Format;
            this.Field13Format = Field13Format;
            this.Field14Format = Field14Format;
            this.Field15Format = Field15Format;
            this.Field16Format = Field16Format;
            this.Field17Format = Field17Format;
            this.Field18Format = Field18Format;
            this.Field19Format = Field19Format;
            this.Field20Format = Field20Format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Capture_Interactive_Retrieve_v1_00_Response", WrapperNamespace="http://services.postcodeanywhere.co.uk/", IsWrapped=true)]
    public partial class Capture_Interactive_Retrieve_v1_00Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.postcodeanywhere.co.uk/", Order=0)]
        public Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00_ArrayOfResults Capture_Interactive_Retrieve_v1_00_Result;
        
        public Capture_Interactive_Retrieve_v1_00Response() {
        }
        
        public Capture_Interactive_Retrieve_v1_00Response(Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00_ArrayOfResults Capture_Interactive_Retrieve_v1_00_Result) {
            this.Capture_Interactive_Retrieve_v1_00_Result = Capture_Interactive_Retrieve_v1_00_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostcodeAnywhere_SoapChannel : Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostcodeAnywhere_SoapClient : System.ServiceModel.ClientBase<Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap>, Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap {
        
        public PostcodeAnywhere_SoapClient() {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeAnywhere_SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeAnywhere_SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap.Capture_Interactive_Retrieve_v1_00(Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request request) {
            return base.Channel.Capture_Interactive_Retrieve_v1_00(request);
        }
        
        public Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00_ArrayOfResults Capture_Interactive_Retrieve_v1_00(
                    string Key, 
                    string Id, 
                    string Field1Format, 
                    string Field2Format, 
                    string Field3Format, 
                    string Field4Format, 
                    string Field5Format, 
                    string Field6Format, 
                    string Field7Format, 
                    string Field8Format, 
                    string Field9Format, 
                    string Field10Format, 
                    string Field11Format, 
                    string Field12Format, 
                    string Field13Format, 
                    string Field14Format, 
                    string Field15Format, 
                    string Field16Format, 
                    string Field17Format, 
                    string Field18Format, 
                    string Field19Format, 
                    string Field20Format) {
            Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request inValue = new Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request();
            inValue.Key = Key;
            inValue.Id = Id;
            inValue.Field1Format = Field1Format;
            inValue.Field2Format = Field2Format;
            inValue.Field3Format = Field3Format;
            inValue.Field4Format = Field4Format;
            inValue.Field5Format = Field5Format;
            inValue.Field6Format = Field6Format;
            inValue.Field7Format = Field7Format;
            inValue.Field8Format = Field8Format;
            inValue.Field9Format = Field9Format;
            inValue.Field10Format = Field10Format;
            inValue.Field11Format = Field11Format;
            inValue.Field12Format = Field12Format;
            inValue.Field13Format = Field13Format;
            inValue.Field14Format = Field14Format;
            inValue.Field15Format = Field15Format;
            inValue.Field16Format = Field16Format;
            inValue.Field17Format = Field17Format;
            inValue.Field18Format = Field18Format;
            inValue.Field19Format = Field19Format;
            inValue.Field20Format = Field20Format;
            Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response retVal = ((Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap)(this)).Capture_Interactive_Retrieve_v1_00(inValue);
            return retVal.Capture_Interactive_Retrieve_v1_00_Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response> Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap.Capture_Interactive_Retrieve_v1_00Async(Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request request) {
            return base.Channel.Capture_Interactive_Retrieve_v1_00Async(request);
        }
        
        public System.Threading.Tasks.Task<Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Response> Capture_Interactive_Retrieve_v1_00Async(
                    string Key, 
                    string Id, 
                    string Field1Format, 
                    string Field2Format, 
                    string Field3Format, 
                    string Field4Format, 
                    string Field5Format, 
                    string Field6Format, 
                    string Field7Format, 
                    string Field8Format, 
                    string Field9Format, 
                    string Field10Format, 
                    string Field11Format, 
                    string Field12Format, 
                    string Field13Format, 
                    string Field14Format, 
                    string Field15Format, 
                    string Field16Format, 
                    string Field17Format, 
                    string Field18Format, 
                    string Field19Format, 
                    string Field20Format) {
            Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request inValue = new Gibe.PCAPredict.Retrieve.Capture_Interactive_Retrieve_v1_00Request();
            inValue.Key = Key;
            inValue.Id = Id;
            inValue.Field1Format = Field1Format;
            inValue.Field2Format = Field2Format;
            inValue.Field3Format = Field3Format;
            inValue.Field4Format = Field4Format;
            inValue.Field5Format = Field5Format;
            inValue.Field6Format = Field6Format;
            inValue.Field7Format = Field7Format;
            inValue.Field8Format = Field8Format;
            inValue.Field9Format = Field9Format;
            inValue.Field10Format = Field10Format;
            inValue.Field11Format = Field11Format;
            inValue.Field12Format = Field12Format;
            inValue.Field13Format = Field13Format;
            inValue.Field14Format = Field14Format;
            inValue.Field15Format = Field15Format;
            inValue.Field16Format = Field16Format;
            inValue.Field17Format = Field17Format;
            inValue.Field18Format = Field18Format;
            inValue.Field19Format = Field19Format;
            inValue.Field20Format = Field20Format;
            return ((Gibe.PCAPredict.Retrieve.PostcodeAnywhere_Soap)(this)).Capture_Interactive_Retrieve_v1_00Async(inValue);
        }
    }
}
